import React, { useState, useContext, useEffect, useRef } from 'react';
import { UserContext } from '../UserContext';
import axios from '../axiosInstance';
import { CSVLink } from 'react-csv';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { FaSearch, FaTimes, FaInfoCircle } from 'react-icons/fa';
import '../Pages.css';
import './Pips.css';
